import type { EntityDefinition } from "../entity-types.js";

export const purchaseInvoiceEntity: EntityDefinition = {
  name: "purchaseInvoice",
  pluralName: "purchaseInvoices",
  apiPath: "purchaseInvoices",
  description:
    "Represents a purchase invoice in Business Central. Purchase invoices are used to record purchases of goods and services from vendors.",
  fields: [
    {
      name: "id",
      type: "guid",
      readOnly: true,
      description: "The unique identifier for the purchase invoice.",
    },
    {
      name: "number",
      type: "string",
      description:
        "The purchase invoice number. Auto-generated if not specified.",
      maxLength: 20,
    },
    {
      name: "invoiceDate",
      type: "date",
      description: "The date of the purchase invoice.",
    },
    {
      name: "postingDate",
      type: "date",
      description: "The posting date of the purchase invoice.",
    },
    {
      name: "dueDate",
      type: "date",
      description: "The date the payment is due.",
    },
    {
      name: "vendorInvoiceNumber",
      type: "string",
      description: "The vendor's invoice number.",
      maxLength: 35,
    },
    {
      name: "vendorId",
      type: "guid",
      description: "The unique identifier of the vendor.",
    },
    {
      name: "vendorNumber",
      type: "string",
      description: "The number of the vendor.",
      maxLength: 20,
    },
    {
      name: "vendorName",
      type: "string",
      description: "The name of the vendor.",
      maxLength: 100,
    },
    {
      name: "payToName",
      type: "string",
      description: "The pay-to name.",
      maxLength: 100,
    },
    {
      name: "payToVendorId",
      type: "guid",
      description: "The unique identifier of the pay-to vendor.",
    },
    {
      name: "payToVendorNumber",
      type: "string",
      description: "The number of the pay-to vendor.",
      maxLength: 20,
    },
    {
      name: "buyFromAddressLine1",
      type: "string",
      description: "The first line of the buy-from address.",
      maxLength: 100,
    },
    {
      name: "buyFromAddressLine2",
      type: "string",
      description: "The second line of the buy-from address.",
      maxLength: 50,
    },
    {
      name: "buyFromCity",
      type: "string",
      description: "The city of the buy-from address.",
      maxLength: 30,
    },
    {
      name: "buyFromState",
      type: "string",
      description: "The state of the buy-from address.",
      maxLength: 30,
    },
    {
      name: "buyFromCountry",
      type: "string",
      description: "The country/region code of the buy-from address.",
      maxLength: 10,
    },
    {
      name: "buyFromPostCode",
      type: "string",
      description: "The postal code of the buy-from address.",
      maxLength: 20,
    },
    {
      name: "payToAddressLine1",
      type: "string",
      description: "The first line of the pay-to address.",
      maxLength: 100,
    },
    {
      name: "payToAddressLine2",
      type: "string",
      description: "The second line of the pay-to address.",
      maxLength: 50,
    },
    {
      name: "payToCity",
      type: "string",
      description: "The city of the pay-to address.",
      maxLength: 30,
    },
    {
      name: "payToState",
      type: "string",
      description: "The state of the pay-to address.",
      maxLength: 30,
    },
    {
      name: "payToCountry",
      type: "string",
      description: "The country/region code of the pay-to address.",
      maxLength: 10,
    },
    {
      name: "payToPostCode",
      type: "string",
      description: "The postal code of the pay-to address.",
      maxLength: 20,
    },
    {
      name: "shipToName",
      type: "string",
      description: "The ship-to name.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine1",
      type: "string",
      description: "The first line of the ship-to address.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine2",
      type: "string",
      description: "The second line of the ship-to address.",
      maxLength: 50,
    },
    {
      name: "shipToCity",
      type: "string",
      description: "The city of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToState",
      type: "string",
      description: "The state of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToCountry",
      type: "string",
      description: "The country/region code of the ship-to address.",
      maxLength: 10,
    },
    {
      name: "shipToPostCode",
      type: "string",
      description: "The postal code of the ship-to address.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension1Code",
      type: "string",
      description: "The code of the first shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension2Code",
      type: "string",
      description: "The code of the second shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "currencyId",
      type: "guid",
      description: "The unique identifier of the currency.",
    },
    {
      name: "currencyCode",
      type: "string",
      description: "The currency code for the invoice.",
      maxLength: 10,
    },
    {
      name: "pricesIncludeTax",
      type: "boolean",
      readOnly: true,
      description: "Whether prices on the invoice include tax.",
    },
    {
      name: "paymentTermsId",
      type: "guid",
      description: "The unique identifier of the payment terms.",
    },
    {
      name: "shipmentMethodId",
      type: "guid",
      description: "The unique identifier of the shipment method.",
    },
    {
      name: "purchaser",
      type: "string",
      description: "The purchaser code.",
      maxLength: 20,
    },
    {
      name: "discountAmount",
      type: "decimal",
      description: "The invoice discount amount.",
    },
    {
      name: "discountAppliedBeforeTax",
      type: "boolean",
      description: "Whether the discount is applied before tax.",
    },
    {
      name: "totalAmountExcludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount excluding tax.",
    },
    {
      name: "totalTaxAmount",
      type: "decimal",
      readOnly: true,
      description: "The total tax amount.",
    },
    {
      name: "totalAmountIncludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount including tax.",
    },
    {
      name: "status",
      type: "enum",
      description: "The status of the purchase invoice.",
      enumValues: [" ", "Draft", "In Review", "Open", "Paid", "Canceled", "Corrective"],
    },
    {
      name: "lastModifiedDateTime",
      type: "datetime",
      readOnly: true,
      description: "The date and time the purchase invoice was last modified.",
    },
  ],
  navigationProperties: [
    {
      name: "vendor",
      targetEntity: "vendor",
      isCollection: false,
      description: "The vendor for the purchase invoice.",
    },
    {
      name: "currency",
      targetEntity: "currency",
      isCollection: false,
      description: "The currency for the purchase invoice.",
    },
    {
      name: "paymentTerm",
      targetEntity: "paymentTerm",
      isCollection: false,
      description: "The payment terms for the purchase invoice.",
    },
    {
      name: "shipmentMethod",
      targetEntity: "shipmentMethod",
      isCollection: false,
      description: "The shipment method for the purchase invoice.",
    },
    {
      name: "purchaseInvoiceLines",
      targetEntity: "purchaseInvoiceLine",
      isCollection: true,
      description: "The line items of the purchase invoice.",
    },
    {
      name: "dimensionSetLines",
      targetEntity: "dimensionSetLine",
      isCollection: true,
      description: "The dimension set lines for the purchase invoice.",
    },
    {
      name: "pdfDocument",
      targetEntity: "pdfDocument",
      isCollection: false,
      description: "The PDF document for the purchase invoice.",
    },
    {
      name: "attachments",
      targetEntity: "attachment",
      isCollection: true,
      description: "The file attachments for the purchase invoice.",
    },
  ],
  boundActions: [
    {
      name: "post",
      description:
        "Posts the purchase invoice. This creates a posted purchase invoice and associated ledger entries.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.post",
    },
    {
      name: "postAndSend",
      description:
        "Posts the purchase invoice and sends it.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.postAndSend",
    },
  ],
};
