import type { EntityDefinition } from "../entity-types.js";

export const purchaseOrderEntity: EntityDefinition = {
  name: "purchaseOrder",
  pluralName: "purchaseOrders",
  apiPath: "purchaseOrders",
  description:
    "Represents a purchase order in Business Central. Purchase orders are used to manage purchases of goods and services from vendors.",
  fields: [
    {
      name: "id",
      type: "guid",
      readOnly: true,
      description: "The unique identifier for the purchase order.",
    },
    {
      name: "number",
      type: "string",
      description:
        "The purchase order number. Auto-generated if not specified.",
      maxLength: 20,
    },
    {
      name: "orderDate",
      type: "date",
      description: "The date of the purchase order.",
    },
    {
      name: "postingDate",
      type: "date",
      description: "The posting date of the purchase order.",
    },
    {
      name: "vendorId",
      type: "guid",
      description: "The unique identifier of the vendor.",
    },
    {
      name: "vendorNumber",
      type: "string",
      description: "The number of the vendor.",
      maxLength: 20,
    },
    {
      name: "vendorName",
      type: "string",
      description: "The name of the vendor.",
      maxLength: 100,
    },
    {
      name: "buyFromAddressLine1",
      type: "string",
      description: "The first line of the buy-from address.",
      maxLength: 100,
    },
    {
      name: "buyFromAddressLine2",
      type: "string",
      description: "The second line of the buy-from address.",
      maxLength: 50,
    },
    {
      name: "buyFromCity",
      type: "string",
      description: "The city of the buy-from address.",
      maxLength: 30,
    },
    {
      name: "buyFromState",
      type: "string",
      description: "The state of the buy-from address.",
      maxLength: 30,
    },
    {
      name: "buyFromCountry",
      type: "string",
      description: "The country/region code of the buy-from address.",
      maxLength: 10,
    },
    {
      name: "buyFromPostCode",
      type: "string",
      description: "The postal code of the buy-from address.",
      maxLength: 20,
    },
    {
      name: "payToName",
      type: "string",
      description: "The pay-to name.",
      maxLength: 100,
    },
    {
      name: "payToVendorId",
      type: "guid",
      description: "The unique identifier of the pay-to vendor.",
    },
    {
      name: "payToVendorNumber",
      type: "string",
      description: "The number of the pay-to vendor.",
      maxLength: 20,
    },
    {
      name: "payToAddressLine1",
      type: "string",
      description: "The first line of the pay-to address.",
      maxLength: 100,
    },
    {
      name: "payToAddressLine2",
      type: "string",
      description: "The second line of the pay-to address.",
      maxLength: 50,
    },
    {
      name: "payToCity",
      type: "string",
      description: "The city of the pay-to address.",
      maxLength: 30,
    },
    {
      name: "payToState",
      type: "string",
      description: "The state of the pay-to address.",
      maxLength: 30,
    },
    {
      name: "payToCountry",
      type: "string",
      description: "The country/region code of the pay-to address.",
      maxLength: 10,
    },
    {
      name: "payToPostCode",
      type: "string",
      description: "The postal code of the pay-to address.",
      maxLength: 20,
    },
    {
      name: "shipToName",
      type: "string",
      description: "The ship-to name.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine1",
      type: "string",
      description: "The first line of the ship-to address.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine2",
      type: "string",
      description: "The second line of the ship-to address.",
      maxLength: 50,
    },
    {
      name: "shipToCity",
      type: "string",
      description: "The city of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToState",
      type: "string",
      description: "The state of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToCountry",
      type: "string",
      description: "The country/region code of the ship-to address.",
      maxLength: 10,
    },
    {
      name: "shipToPostCode",
      type: "string",
      description: "The postal code of the ship-to address.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension1Code",
      type: "string",
      description: "The code of the first shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension2Code",
      type: "string",
      description: "The code of the second shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "currencyId",
      type: "guid",
      description: "The unique identifier of the currency.",
    },
    {
      name: "currencyCode",
      type: "string",
      description: "The currency code for the order.",
      maxLength: 10,
    },
    {
      name: "pricesIncludeTax",
      type: "boolean",
      readOnly: true,
      description: "Whether prices on the order include tax.",
    },
    {
      name: "paymentTermsId",
      type: "guid",
      description: "The unique identifier of the payment terms.",
    },
    {
      name: "shipmentMethodId",
      type: "guid",
      description: "The unique identifier of the shipment method.",
    },
    {
      name: "purchaser",
      type: "string",
      description: "The purchaser code assigned to the order.",
      maxLength: 20,
    },
    {
      name: "requestedReceiptDate",
      type: "date",
      description: "The requested receipt date.",
    },
    {
      name: "discountAmount",
      type: "decimal",
      description: "The invoice discount amount.",
    },
    {
      name: "discountAppliedBeforeTax",
      type: "boolean",
      description: "Whether the discount is applied before tax.",
    },
    {
      name: "totalAmountExcludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount excluding tax.",
    },
    {
      name: "totalTaxAmount",
      type: "decimal",
      readOnly: true,
      description: "The total tax amount.",
    },
    {
      name: "totalAmountIncludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount including tax.",
    },
    {
      name: "fullyReceived",
      type: "boolean",
      description: "Whether the order has been fully received.",
    },
    {
      name: "status",
      type: "enum",
      description: "The status of the purchase order.",
      enumValues: ["Draft", "In Review", "Open"],
    },
    {
      name: "lastModifiedDateTime",
      type: "datetime",
      readOnly: true,
      description: "The date and time the purchase order was last modified.",
    },
  ],
  navigationProperties: [
    {
      name: "vendor",
      targetEntity: "vendor",
      isCollection: false,
      description: "The vendor for the purchase order.",
    },
    {
      name: "currency",
      targetEntity: "currency",
      isCollection: false,
      description: "The currency for the purchase order.",
    },
    {
      name: "paymentTerm",
      targetEntity: "paymentTerm",
      isCollection: false,
      description: "The payment terms for the purchase order.",
    },
    {
      name: "shipmentMethod",
      targetEntity: "shipmentMethod",
      isCollection: false,
      description: "The shipment method for the purchase order.",
    },
    {
      name: "purchaseOrderLines",
      targetEntity: "purchaseOrderLine",
      isCollection: true,
      description: "The line items of the purchase order.",
    },
    {
      name: "dimensionSetLines",
      targetEntity: "dimensionSetLine",
      isCollection: true,
      description: "The dimension set lines for the purchase order.",
    },
  ],
  boundActions: [
    {
      name: "receiveAndInvoice",
      description:
        "Receives and invoices the purchase order. This posts the receipt and creates a posted purchase invoice.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.receiveAndInvoice",
    },
  ],
};
