import type { EntityDefinition } from "../entity-types.js";

export const salesQuoteEntity: EntityDefinition = {
  name: "salesQuote",
  pluralName: "salesQuotes",
  apiPath: "salesQuotes",
  description:
    "Represents a sales quote in Business Central. Sales quotes are preliminary documents sent to customers before an order or invoice is created.",
  fields: [
    {
      name: "id",
      type: "guid",
      readOnly: true,
      description: "The unique identifier for the sales quote.",
    },
    {
      name: "number",
      type: "string",
      description:
        "The sales quote number. Auto-generated if not specified.",
      maxLength: 20,
    },
    {
      name: "externalDocumentNumber",
      type: "string",
      description: "The external document number.",
      maxLength: 35,
    },
    {
      name: "documentDate",
      type: "date",
      description: "The date of the sales quote.",
    },
    {
      name: "postingDate",
      type: "date",
      description: "The posting date of the sales quote.",
    },
    {
      name: "dueDate",
      type: "date",
      description: "The due date of the sales quote.",
    },
    {
      name: "customerId",
      type: "guid",
      description: "The unique identifier of the customer.",
    },
    {
      name: "customerNumber",
      type: "string",
      description: "The number of the customer.",
      maxLength: 20,
    },
    {
      name: "customerName",
      type: "string",
      description: "The name of the customer.",
      maxLength: 100,
    },
    {
      name: "billToName",
      type: "string",
      description: "The bill-to name.",
      maxLength: 100,
    },
    {
      name: "billToCustomerId",
      type: "guid",
      description: "The unique identifier of the bill-to customer.",
    },
    {
      name: "billToCustomerNumber",
      type: "string",
      description: "The number of the bill-to customer.",
      maxLength: 20,
    },
    {
      name: "shipToName",
      type: "string",
      description: "The ship-to name.",
      maxLength: 100,
    },
    {
      name: "shipToContact",
      type: "string",
      description: "The ship-to contact person.",
      maxLength: 100,
    },
    {
      name: "sellToAddressLine1",
      type: "string",
      description: "The first line of the sell-to address.",
      maxLength: 100,
    },
    {
      name: "sellToAddressLine2",
      type: "string",
      description: "The second line of the sell-to address.",
      maxLength: 50,
    },
    {
      name: "sellToCity",
      type: "string",
      description: "The city of the sell-to address.",
      maxLength: 30,
    },
    {
      name: "sellToCountry",
      type: "string",
      description: "The country/region code of the sell-to address.",
      maxLength: 10,
    },
    {
      name: "sellToState",
      type: "string",
      description: "The state of the sell-to address.",
      maxLength: 30,
    },
    {
      name: "sellToPostCode",
      type: "string",
      description: "The postal code of the sell-to address.",
      maxLength: 20,
    },
    {
      name: "billToAddressLine1",
      type: "string",
      description: "The first line of the bill-to address.",
      maxLength: 100,
    },
    {
      name: "billToAddressLine2",
      type: "string",
      description: "The second line of the bill-to address.",
      maxLength: 50,
    },
    {
      name: "billToCity",
      type: "string",
      description: "The city of the bill-to address.",
      maxLength: 30,
    },
    {
      name: "billToCountry",
      type: "string",
      description: "The country/region code of the bill-to address.",
      maxLength: 10,
    },
    {
      name: "billToState",
      type: "string",
      description: "The state of the bill-to address.",
      maxLength: 30,
    },
    {
      name: "billToPostCode",
      type: "string",
      description: "The postal code of the bill-to address.",
      maxLength: 20,
    },
    {
      name: "shipToAddressLine1",
      type: "string",
      description: "The first line of the ship-to address.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine2",
      type: "string",
      description: "The second line of the ship-to address.",
      maxLength: 50,
    },
    {
      name: "shipToCity",
      type: "string",
      description: "The city of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToCountry",
      type: "string",
      description: "The country/region code of the ship-to address.",
      maxLength: 10,
    },
    {
      name: "shipToState",
      type: "string",
      description: "The state of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToPostCode",
      type: "string",
      description: "The postal code of the ship-to address.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension1Code",
      type: "string",
      description: "The code of the first shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension2Code",
      type: "string",
      description: "The code of the second shortcut dimension.",
      maxLength: 20,
    },
    {
      name: "currencyId",
      type: "guid",
      description: "The unique identifier of the currency.",
    },
    {
      name: "currencyCode",
      type: "string",
      description: "The currency code for the quote.",
      maxLength: 10,
    },
    {
      name: "pricesIncludeTax",
      type: "boolean",
      readOnly: true,
      description: "Whether prices on the quote include tax.",
    },
    {
      name: "paymentTermsId",
      type: "guid",
      description: "The unique identifier of the payment terms.",
    },
    {
      name: "shipmentMethodId",
      type: "guid",
      description: "The unique identifier of the shipment method.",
    },
    {
      name: "salesperson",
      type: "string",
      description: "The salesperson code assigned to the quote.",
      maxLength: 20,
    },
    {
      name: "discountAmount",
      type: "decimal",
      description: "The invoice discount amount.",
    },
    {
      name: "discountAppliedBeforeTax",
      type: "boolean",
      description: "Whether the discount is applied before tax.",
    },
    {
      name: "totalAmountExcludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount excluding tax.",
    },
    {
      name: "totalTaxAmount",
      type: "decimal",
      readOnly: true,
      description: "The total tax amount.",
    },
    {
      name: "totalAmountIncludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount including tax.",
    },
    {
      name: "status",
      type: "enum",
      description: "The status of the sales quote.",
      enumValues: ["Draft", "Sent"],
    },
    {
      name: "sentDate",
      type: "datetime",
      readOnly: true,
      description: "The date and time the quote was sent.",
    },
    {
      name: "validUntilDate",
      type: "date",
      description: "The date until which the quote is valid.",
    },
    {
      name: "acceptedDate",
      type: "date",
      description: "The date the quote was accepted.",
    },
    {
      name: "lastModifiedDateTime",
      type: "datetime",
      readOnly: true,
      description: "The date and time the sales quote was last modified.",
    },
    {
      name: "phoneNumber",
      type: "string",
      description: "The phone number associated with the quote.",
      maxLength: 30,
    },
    {
      name: "email",
      type: "string",
      description: "The email address associated with the quote.",
      maxLength: 80,
    },
  ],
  navigationProperties: [
    {
      name: "customer",
      targetEntity: "customer",
      isCollection: false,
      description: "The customer for the sales quote.",
    },
    {
      name: "currency",
      targetEntity: "currency",
      isCollection: false,
      description: "The currency for the sales quote.",
    },
    {
      name: "paymentTerm",
      targetEntity: "paymentTerm",
      isCollection: false,
      description: "The payment terms for the sales quote.",
    },
    {
      name: "shipmentMethod",
      targetEntity: "shipmentMethod",
      isCollection: false,
      description: "The shipment method for the sales quote.",
    },
    {
      name: "salesQuoteLines",
      targetEntity: "salesQuoteLine",
      isCollection: true,
      description: "The line items of the sales quote.",
    },
    {
      name: "dimensionSetLines",
      targetEntity: "dimensionSetLine",
      isCollection: true,
      description: "The dimension set lines for the sales quote.",
    },
    {
      name: "pdfDocument",
      targetEntity: "pdfDocument",
      isCollection: false,
      description: "The PDF document for the sales quote.",
    },
    {
      name: "attachments",
      targetEntity: "attachment",
      isCollection: true,
      description: "The file attachments for the sales quote.",
    },
  ],
  boundActions: [
    {
      name: "makeInvoice",
      description:
        "Converts the sales quote to a sales invoice.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.makeInvoice",
    },
    {
      name: "makeOrder",
      description:
        "Converts the sales quote to a sales order.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.makeOrder",
    },
    {
      name: "send",
      description:
        "Sends the sales quote to the customer via email.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.send",
    },
  ],
};
