import type { EntityDefinition } from "../entity-types.js";

export const salesOrderEntity: EntityDefinition = {
  name: "salesOrder",
  pluralName: "salesOrders",
  apiPath: "salesOrders",
  description:
    "Represents a sales order in Business Central. Sales orders are used to manage the sale and delivery of products and services to customers.",
  fields: [
    {
      name: "id",
      type: "guid",
      readOnly: true,
      description: "The unique identifier for the sales order.",
    },
    {
      name: "number",
      type: "string",
      description:
        "The sales order number. Auto-generated if not specified.",
      maxLength: 20,
    },
    {
      name: "externalDocumentNumber",
      type: "string",
      description:
        "The external document number, such as the customer's purchase order number.",
      maxLength: 35,
    },
    {
      name: "orderDate",
      type: "date",
      description: "The date the sales order was created.",
    },
    {
      name: "postingDate",
      type: "date",
      description: "The date the sales order will be posted.",
    },
    {
      name: "customerId",
      type: "guid",
      description: "The unique identifier of the customer for the order.",
    },
    {
      name: "customerNumber",
      type: "string",
      description: "The number of the customer for the order.",
      maxLength: 20,
    },
    {
      name: "customerName",
      type: "string",
      description: "The name of the customer for the order.",
      maxLength: 100,
    },
    {
      name: "billToName",
      type: "string",
      description: "The bill-to name.",
      maxLength: 100,
    },
    {
      name: "billToCustomerId",
      type: "guid",
      description: "The unique identifier of the bill-to customer.",
    },
    {
      name: "billToCustomerNumber",
      type: "string",
      description: "The number of the bill-to customer.",
      maxLength: 20,
    },
    {
      name: "shipToName",
      type: "string",
      description: "The ship-to name.",
      maxLength: 100,
    },
    {
      name: "shipToContact",
      type: "string",
      description: "The ship-to contact person.",
      maxLength: 100,
    },
    {
      name: "sellToAddressLine1",
      type: "string",
      description: "The first line of the sell-to address.",
      maxLength: 100,
    },
    {
      name: "sellToAddressLine2",
      type: "string",
      description: "The second line of the sell-to address.",
      maxLength: 50,
    },
    {
      name: "sellToCity",
      type: "string",
      description: "The city of the sell-to address.",
      maxLength: 30,
    },
    {
      name: "sellToCountry",
      type: "string",
      description: "The country/region code of the sell-to address.",
      maxLength: 10,
    },
    {
      name: "sellToState",
      type: "string",
      description: "The state of the sell-to address.",
      maxLength: 30,
    },
    {
      name: "sellToPostCode",
      type: "string",
      description: "The postal code of the sell-to address.",
      maxLength: 20,
    },
    {
      name: "billToAddressLine1",
      type: "string",
      description: "The first line of the bill-to address.",
      maxLength: 100,
    },
    {
      name: "billToAddressLine2",
      type: "string",
      description: "The second line of the bill-to address.",
      maxLength: 50,
    },
    {
      name: "billToCity",
      type: "string",
      description: "The city of the bill-to address.",
      maxLength: 30,
    },
    {
      name: "billToCountry",
      type: "string",
      description: "The country/region code of the bill-to address.",
      maxLength: 10,
    },
    {
      name: "billToState",
      type: "string",
      description: "The state of the bill-to address.",
      maxLength: 30,
    },
    {
      name: "billToPostCode",
      type: "string",
      description: "The postal code of the bill-to address.",
      maxLength: 20,
    },
    {
      name: "shipToAddressLine1",
      type: "string",
      description: "The first line of the ship-to address.",
      maxLength: 100,
    },
    {
      name: "shipToAddressLine2",
      type: "string",
      description: "The second line of the ship-to address.",
      maxLength: 50,
    },
    {
      name: "shipToCity",
      type: "string",
      description: "The city of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToCountry",
      type: "string",
      description: "The country/region code of the ship-to address.",
      maxLength: 10,
    },
    {
      name: "shipToState",
      type: "string",
      description: "The state of the ship-to address.",
      maxLength: 30,
    },
    {
      name: "shipToPostCode",
      type: "string",
      description: "The postal code of the ship-to address.",
      maxLength: 20,
    },
    {
      name: "shortcutDimension1Code",
      type: "string",
      description: "The code of the first shortcut dimension (typically Department).",
      maxLength: 20,
    },
    {
      name: "shortcutDimension2Code",
      type: "string",
      description: "The code of the second shortcut dimension (typically Project).",
      maxLength: 20,
    },
    {
      name: "currencyId",
      type: "guid",
      description: "The unique identifier of the currency for the order.",
    },
    {
      name: "currencyCode",
      type: "string",
      description: "The currency code for the order.",
      maxLength: 10,
    },
    {
      name: "pricesIncludeTax",
      type: "boolean",
      readOnly: true,
      description: "Whether prices on the order include tax.",
    },
    {
      name: "paymentTermsId",
      type: "guid",
      description: "The unique identifier of the payment terms.",
    },
    {
      name: "shipmentMethodId",
      type: "guid",
      description: "The unique identifier of the shipment method.",
    },
    {
      name: "salesperson",
      type: "string",
      description: "The salesperson code assigned to the order.",
      maxLength: 20,
    },
    {
      name: "partialShipping",
      type: "boolean",
      description: "Whether partial shipping is allowed for the order.",
    },
    {
      name: "requestedDeliveryDate",
      type: "date",
      description: "The requested delivery date for the order.",
    },
    {
      name: "discountAmount",
      type: "decimal",
      description: "The invoice discount amount applied to the order.",
    },
    {
      name: "discountAppliedBeforeTax",
      type: "boolean",
      description: "Whether the discount is applied before tax.",
    },
    {
      name: "totalAmountExcludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount of the order excluding tax.",
    },
    {
      name: "totalTaxAmount",
      type: "decimal",
      readOnly: true,
      description: "The total tax amount for the order.",
    },
    {
      name: "totalAmountIncludingTax",
      type: "decimal",
      readOnly: true,
      description: "The total amount of the order including tax.",
    },
    {
      name: "fullyShipped",
      type: "boolean",
      description: "Whether the order has been fully shipped.",
    },
    {
      name: "status",
      type: "enum",
      description: "The status of the sales order.",
      enumValues: ["Draft", "In Review", "Open"],
    },
    {
      name: "lastModifiedDateTime",
      type: "datetime",
      readOnly: true,
      description: "The date and time the sales order was last modified.",
    },
    {
      name: "phoneNumber",
      type: "string",
      description: "The phone number associated with the order.",
      maxLength: 30,
    },
    {
      name: "email",
      type: "string",
      description: "The email address associated with the order.",
      maxLength: 80,
    },
  ],
  navigationProperties: [
    {
      name: "customer",
      targetEntity: "customer",
      isCollection: false,
      description: "The customer for the sales order.",
    },
    {
      name: "currency",
      targetEntity: "currency",
      isCollection: false,
      description: "The currency for the sales order.",
    },
    {
      name: "paymentTerm",
      targetEntity: "paymentTerm",
      isCollection: false,
      description: "The payment terms for the sales order.",
    },
    {
      name: "shipmentMethod",
      targetEntity: "shipmentMethod",
      isCollection: false,
      description: "The shipment method for the sales order.",
    },
    {
      name: "salesOrderLines",
      targetEntity: "salesOrderLine",
      isCollection: true,
      description: "The line items of the sales order.",
    },
    {
      name: "dimensionSetLines",
      targetEntity: "dimensionSetLine",
      isCollection: true,
      description: "The dimension set lines for the sales order.",
    },
    {
      name: "pdfDocument",
      targetEntity: "pdfDocument",
      isCollection: false,
      description: "The PDF document for the sales order.",
    },
    {
      name: "attachments",
      targetEntity: "attachment",
      isCollection: true,
      description: "The file attachments for the sales order.",
    },
  ],
  boundActions: [
    {
      name: "shipAndInvoice",
      description:
        "Ships and invoices the sales order. This posts the shipment and creates a posted sales invoice.",
      httpMethod: "POST",
      navPath: "Microsoft.NAV.shipAndInvoice",
    },
  ],
};
